### ISSUE TITLE
"Unable to connect to the remote server" Crash

### ISSUE THREAD

**Issue by Diyagi** [electr0sheep/EurekaTrackerAutoPopper#1]
```
2022-05-16 09:40:24.664 -03:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unable to connect to the remote server)
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at EurekaTrackerAutoPopper.EurekaTrackerWrapper.WebRequests.FindTracker(UInt32 dataCenterId, Int16 zoneId) in \\wsl$\Ubuntu-20.04\home\diyagi\projects\EurekaTrackerAutoPopper\EurekaTrackerAutoPopper\EurekaTrackerWrapper\WebRequests.cs:line 47
   at EurekaTrackerAutoPopper.Plugin.<TerritoryChangePoll>b__49_0() in \\wsl$\Ubuntu-20.04\home\diyagi\projects\EurekaTrackerAutoPopper\EurekaTrackerAutoPopper\PluginUI.cs:line 16
   --- End of inner exception stack trace ---
```

Maybe a try catch could prevent this ?

**Comment by Diyagi** [comment]
Actually, the SSL certificate for eureka tracker website expired...

**Comment by electr0sheep** [comment]
Weird that the SSL cert expired lol. Probably a good idea to try/catch it anyway, so I merged your PR
